### ISSUE TITLE
Implement four arithmetic operations

### ISSUE THREAD

**Issue by songhyun99** [songhyun99/gitPractice#1]
### Description

four arithmetic operations

### Tasks
- [x] Implement add function
- [ ] Implement sub function
- [ ] Implement mul function
- [ ] Implement div function

### References
- [LinkText](LinkAddress)
