### ISSUE TITLE
Implement Subtract function

### ISSUE THREAD

**Issue by gus6615** [songhyun99/gitPractice#2]
### Description

Implement Subtract function for arithmetic operations

### To-Do

- [x] Input two argument form user
- [x] Get muscle for you
- [x] Have a good day :)

### Pseudo-Code

1) 두 숫자(a, b)를 입력 받는다.
2) a에서 b를 뺀 값을 c에 저장한다.
3) c를 반환한다.
